### ISSUE TITLE
-IsIndeterminate $true does not remove "0%" from ProgressBar

### ISSUE THREAD

**Issue by klaauser** [Tiberriver256/PoshProgressBar#10]
Using the -IsIndeterminate $true flag does not remove the "0%" text from the ProgressBar - I've tried all types: Circle, Vertical, and Horizontal.

`$progressbar = New-ProgressBar -MaterialDesign -Type Circle -PrimaryColor Pink -AccentColor LightBlue -Size Medium -Theme Light -IsIndeterminate $true`
![isindeterminatecircle](https://user-images.githubusercontent.com/9086260/26841370-49f0f01c-4ab7-11e7-8410-8b697f5318d9.png)

Setting the -IsIndeterminate flag to $false shows the "0%" text but does not show the actually ProgressBar

`$progressbar = New-ProgressBar -MaterialDesign -Type Circle -PrimaryColor Pink -AccentColor LightBlue -Size Medium -Theme Light -IsIndeterminate $false`
![isindeterminatefalsecircle](https://user-images.githubusercontent.com/9086260/26841489-a4f8f842-4ab7-11e7-92c3-c30287c2bcbc.png)

**Comment by Tiberriver256** [comment]
Thanks @klaauser. This should do it. Could you test the code from Github here to see if that was what you are looking for?

If it looks good to you I'll post the updated version out to PowerShell gallery.

**Comment by klaauser** [comment]
Looks like it fixes `-IsIndeterminate:$true`

Doesn’t fix it for `-IsIndeterminate:$false` and now I’m getting `A parameter cannot be found that matches parameter name 'IconPath'.` when trying to use IconPath (was in my original code)

**Comment by HWO365manager** [comment]
The fix for the % being displayed when -IsIndeterminate $true has not been implemented in the released code.

**Comment by adudeguy** [comment]
Has a fix for this been released? When modifying the module as specified by @klaauser (adding "Visibility="Hidden" to line 141) the progress bar does not show at all. I would like to kindly request a solution for this.

**Comment by Tiberriver256** [comment]
Hi guys and thank you for the continued interest. I had somewhat abandoned this project but I'm back in to hopefully tune things up a bit.

1st thing I realized which is related to the problem @klaauser mentioned with `-IconPath` being a missing option was that my 2016 self had been publishing updates to the Powershell Gallery and my blog without actually updating the code here on the repository! 😲😳😓

So I updated the code here to match 0.132 which is the latest version published on the Gallery and I also updated the code to fix the issue mentioned here.

The example given for `-IsIndeterminate $false` with the progress bar not being displayed at all is due to the way Material Design does circle progress bars. When the percentage is 0% there is no progress bar displayed. If you assign any percentage to it though it will show up like this:

![image](https://user-images.githubusercontent.com/6989492/68261635-bd147c80-000e-11ea-96e7-a3be2905a428.png)

I just pushed version .133 out to the gallery which has this fix included in it. Let me know if you run into any issues.
